pipeline{
   agent any
   stages{
      stage('checkout'){
         steps{
            checkout scmGit(branches: [[name: '*/main']],
                            userRemoteConfigs: [[credentialsId: 'github',
                            url: 'https://github.com/Kavana1997/java_calculator_app_itd.git']])
         }
      }
      
      stage('unit test'){
         steps{
            sh '''
            cd ./java_app
            mvn test
            '''
         }
      }

      stage('integration test'){
         steps{
            dir('./java_app'){
               sh 'mvn integration-test'           
            }
         }
      }

      stage('load testing'){
         steps{
            dir('./java_app'){
               sh 'mvn verify'
            }
         }
      }
   }
}