pipeline{
   agent any
   tools{
      maven 'maven'
   }
   stages{
      stage('checkout'){
         steps{
            checkout scmGit(branches: [[name: '*/main']],
                            userRemoteConfigs: [[credentialsId: 'github',
                            url: 'https://github.com/Kavana1997/java_calculator_app_itd.git']])
         }
      }
      
      stage('unit test'){
         steps{
            sh '''
            cd ./java_app-main/calculator_app
            mvn test
            '''
         }
      }

      stage('integration test'){
         steps{
            dir('./java_app-main/calculator_app'){
               sh 'mvn integration-test'           
            }
         }
      }

      stage('load testing'){
         steps{
            catchError(stageResult: 'FAILURE', buildResult: 'SUCCESS'){
               dir('./java_app-main/calculator_app'){
               sh 'mvn clean verify'
               }
            }
         }
      }
      stage('deploy tomcat10'){
         steps{
            script{
               deploy adapter: [tomcat9(credentialsId:'tomcat_kavana', url: 'http://13.127.77.9:8080')]
               contextPath:'/calculator'
               war: './java_app-main/calculator_app/target/calculator.war'
            }
         }

      }
   }
}